# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\bodyWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_bodyForm(object):
    def setupUi(self, bodyForm):
        bodyForm.setObjectName("bodyForm")
        bodyForm.resize(626, 328)
        bodyForm.setMinimumSize(QtCore.QSize(626, 328))
        bodyForm.setMaximumSize(QtCore.QSize(900, 900))
        bodyForm.setToolTipDuration(5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(bodyForm)
        self.horizontalLayout_3.setContentsMargins(6, 3, 6, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.GB_body = QtWidgets.QGroupBox(bodyForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GB_body.sizePolicy().hasHeightForWidth())
        self.GB_body.setSizePolicy(sizePolicy)
        self.GB_body.setObjectName("GB_body")
        self.gridLayout = QtWidgets.QGridLayout(self.GB_body)
        self.gridLayout.setContentsMargins(9, 5, 9, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.GB_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_ok = QtWidgets.QPushButton(self.frame)
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout.addWidget(self.btn_ok)
        self.btn_cancel = QtWidgets.QPushButton(self.frame)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.gridLayout.addWidget(self.frame, 9, 1, 1, 1)
        self.cb_preset = QtWidgets.QComboBox(self.GB_body)
        self.cb_preset.setObjectName("cb_preset")
        self.gridLayout.addWidget(self.cb_preset, 0, 1, 1, 1)
        self.lbl_preset = QtWidgets.QLabel(self.GB_body)
        self.lbl_preset.setObjectName("lbl_preset")
        self.gridLayout.addWidget(self.lbl_preset, 0, 0, 1, 1)
        self.lbl_sma = QtWidgets.QLabel(self.GB_body)
        self.lbl_sma.setObjectName("lbl_sma")
        self.gridLayout.addWidget(self.lbl_sma, 4, 0, 1, 1)
        self.lbl_inc = QtWidgets.QLabel(self.GB_body)
        self.lbl_inc.setObjectName("lbl_inc")
        self.gridLayout.addWidget(self.lbl_inc, 6, 0, 1, 1)
        self.lbl_radius = QtWidgets.QLabel(self.GB_body)
        self.lbl_radius.setObjectName("lbl_radius")
        self.gridLayout.addWidget(self.lbl_radius, 3, 0, 1, 1)
        self.lbl_mass = QtWidgets.QLabel(self.GB_body)
        self.lbl_mass.setObjectName("lbl_mass")
        self.gridLayout.addWidget(self.lbl_mass, 2, 0, 1, 1)
        self.lbl_vel = QtWidgets.QLabel(self.GB_body)
        self.lbl_vel.setObjectName("lbl_vel")
        self.gridLayout.addWidget(self.lbl_vel, 5, 0, 1, 1)
        self.lbl_name = QtWidgets.QLabel(self.GB_body)
        self.lbl_name.setObjectName("lbl_name")
        self.gridLayout.addWidget(self.lbl_name, 1, 0, 1, 1)
        self.le_radius = QtWidgets.QLineEdit(self.GB_body)
        self.le_radius.setObjectName("le_radius")
        self.gridLayout.addWidget(self.le_radius, 3, 1, 1, 1)
        self.le_sma = QtWidgets.QLineEdit(self.GB_body)
        self.le_sma.setObjectName("le_sma")
        self.gridLayout.addWidget(self.le_sma, 4, 1, 1, 1)
        self.le_inc = QtWidgets.QLineEdit(self.GB_body)
        self.le_inc.setObjectName("le_inc")
        self.gridLayout.addWidget(self.le_inc, 6, 1, 1, 1)
        self.le_vel = QtWidgets.QLineEdit(self.GB_body)
        self.le_vel.setObjectName("le_vel")
        self.gridLayout.addWidget(self.le_vel, 5, 1, 1, 1)
        self.le_mass = QtWidgets.QLineEdit(self.GB_body)
        self.le_mass.setObjectName("le_mass")
        self.gridLayout.addWidget(self.le_mass, 2, 1, 1, 1)
        self.le_name = QtWidgets.QLineEdit(self.GB_body)
        self.le_name.setObjectName("le_name")
        self.gridLayout.addWidget(self.le_name, 1, 1, 1, 1)
        self.btn_color_choose = QtWidgets.QPushButton(self.GB_body)
        self.btn_color_choose.setObjectName("btn_color_choose")
        self.gridLayout.addWidget(self.btn_color_choose, 7, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.frame_2 = QtWidgets.QFrame(self.GB_body)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_color = QtWidgets.QLabel(self.frame_2)
        self.lbl_color.setObjectName("lbl_color")
        self.horizontalLayout_2.addWidget(self.lbl_color)
        self.lbl_col_pixmap = QtWidgets.QLabel(self.frame_2)
        self.lbl_col_pixmap.setText("")
        self.lbl_col_pixmap.setObjectName("lbl_col_pixmap")
        self.horizontalLayout_2.addWidget(self.lbl_col_pixmap)
        self.gridLayout.addWidget(self.frame_2, 7, 0, 1, 1)
        self.lbl_texture = QtWidgets.QLabel(self.GB_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_texture.sizePolicy().hasHeightForWidth())
        self.lbl_texture.setSizePolicy(sizePolicy)
        self.lbl_texture.setObjectName("lbl_texture")
        self.gridLayout.addWidget(self.lbl_texture, 8, 0, 1, 1)
        self.btn_texture = QtWidgets.QPushButton(self.GB_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_texture.sizePolicy().hasHeightForWidth())
        self.btn_texture.setSizePolicy(sizePolicy)
        self.btn_texture.setObjectName("btn_texture")
        self.gridLayout.addWidget(self.btn_texture, 8, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.GB_body)
        self.frame_3 = QtWidgets.QFrame(bodyForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gv_body = GLViewWidget(self.frame_3)
        self.gv_body.setObjectName("gv_body")
        self.verticalLayout.addWidget(self.gv_body)
        self.horizontalLayout_3.addWidget(self.frame_3)

        self.retranslateUi(bodyForm)
        QtCore.QMetaObject.connectSlotsByName(bodyForm)
        bodyForm.setTabOrder(self.le_name, self.le_mass)
        bodyForm.setTabOrder(self.le_mass, self.le_radius)
        bodyForm.setTabOrder(self.le_radius, self.le_sma)
        bodyForm.setTabOrder(self.le_sma, self.le_vel)
        bodyForm.setTabOrder(self.le_vel, self.le_inc)

    def retranslateUi(self, bodyForm):
        _translate = QtCore.QCoreApplication.translate
        bodyForm.setWindowTitle(_translate("bodyForm", "Orbital Body - Edit"))
        self.GB_body.setTitle(_translate("bodyForm", "Orbital Body"))
        self.btn_ok.setText(_translate("bodyForm", "Ok"))
        self.btn_cancel.setText(_translate("bodyForm", "Cancel"))
        self.lbl_preset.setText(_translate("bodyForm", "Preset:"))
        self.lbl_sma.setText(_translate("bodyForm", "Orbit Semi-Major Axis (km):"))
        self.lbl_inc.setText(_translate("bodyForm", "Inclination (deg):"))
        self.lbl_radius.setText(_translate("bodyForm", "Radius (km):"))
        self.lbl_mass.setText(_translate("bodyForm", "Mass (kg):"))
        self.lbl_vel.setText(_translate("bodyForm", "Orbital Velocity (km/s):"))
        self.lbl_name.setText(_translate("bodyForm", "Name:"))
        self.le_radius.setToolTip(_translate("bodyForm", "<html><head/><body><p>Radius of the orbital body, in kilometers.</p></body></html>"))
        self.le_sma.setToolTip(_translate("bodyForm", "<html><head/><body><p>The semi-major axis or mean radius of the orbit in kilometers.</p></body></html>"))
        self.le_inc.setToolTip(_translate("bodyForm", "<html><head/><body><p>Orbital inclination in degrees, 0 to 90.</p></body></html>"))
        self.le_vel.setToolTip(_translate("bodyForm", "<html><head/><body><p>The mean orbital velocity, in kilometers per second.</p></body></html>"))
        self.le_mass.setToolTip(_translate("bodyForm", "<html><head/><body><p>Mass of the body, in kilograms.</p></body></html>"))
        self.le_name.setToolTip(_translate("bodyForm", "<html><head/><body><p>The name of this orbital body.</p></body></html>"))
        self.btn_color_choose.setText(_translate("bodyForm", "Choose Color"))
        self.lbl_color.setText(_translate("bodyForm", "Orbit Color: (Optional)"))
        self.lbl_texture.setText(_translate("bodyForm", "Texture:"))
        self.btn_texture.setText(_translate("bodyForm", "Choose Texture"))

from pyqtgraph.opengl import GLViewWidget
