# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\bodyWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_bodyForm(object):
    def setupUi(self, bodyForm):
        bodyForm.setObjectName("bodyForm")
        bodyForm.resize(356, 253)
        bodyForm.setMinimumSize(QtCore.QSize(356, 253))
        bodyForm.setMaximumSize(QtCore.QSize(356, 253))
        bodyForm.setToolTipDuration(5)
        self.verticalLayout = QtWidgets.QVBoxLayout(bodyForm)
        self.verticalLayout.setContentsMargins(6, 3, 6, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.GB_body = QtWidgets.QGroupBox(bodyForm)
        self.GB_body.setObjectName("GB_body")
        self.gridLayout = QtWidgets.QGridLayout(self.GB_body)
        self.gridLayout.setContentsMargins(9, 5, 9, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_radius = QtWidgets.QLabel(self.GB_body)
        self.lbl_radius.setObjectName("lbl_radius")
        self.gridLayout.addWidget(self.lbl_radius, 3, 0, 1, 1)
        self.cb_star = QtWidgets.QCheckBox(self.GB_body)
        self.cb_star.setObjectName("cb_star")
        self.gridLayout.addWidget(self.cb_star, 1, 1, 1, 1)
        self.le_radius = QtWidgets.QLineEdit(self.GB_body)
        self.le_radius.setObjectName("le_radius")
        self.gridLayout.addWidget(self.le_radius, 3, 1, 1, 1)
        self.le_vel = QtWidgets.QLineEdit(self.GB_body)
        self.le_vel.setObjectName("le_vel")
        self.gridLayout.addWidget(self.le_vel, 5, 1, 1, 1)
        self.le_sma = QtWidgets.QLineEdit(self.GB_body)
        self.le_sma.setObjectName("le_sma")
        self.gridLayout.addWidget(self.le_sma, 4, 1, 1, 1)
        self.le_inc = QtWidgets.QLineEdit(self.GB_body)
        self.le_inc.setObjectName("le_inc")
        self.gridLayout.addWidget(self.le_inc, 6, 1, 1, 1)
        self.le_mass = QtWidgets.QLineEdit(self.GB_body)
        self.le_mass.setObjectName("le_mass")
        self.gridLayout.addWidget(self.le_mass, 2, 1, 1, 1)
        self.le_name = QtWidgets.QLineEdit(self.GB_body)
        self.le_name.setObjectName("le_name")
        self.gridLayout.addWidget(self.le_name, 0, 1, 1, 1)
        self.lbl_inc = QtWidgets.QLabel(self.GB_body)
        self.lbl_inc.setObjectName("lbl_inc")
        self.gridLayout.addWidget(self.lbl_inc, 6, 0, 1, 1)
        self.lbl_name = QtWidgets.QLabel(self.GB_body)
        self.lbl_name.setObjectName("lbl_name")
        self.gridLayout.addWidget(self.lbl_name, 0, 0, 1, 1)
        self.lbl_vel = QtWidgets.QLabel(self.GB_body)
        self.lbl_vel.setObjectName("lbl_vel")
        self.gridLayout.addWidget(self.lbl_vel, 5, 0, 1, 1)
        self.lbl_mass = QtWidgets.QLabel(self.GB_body)
        self.lbl_mass.setObjectName("lbl_mass")
        self.gridLayout.addWidget(self.lbl_mass, 2, 0, 1, 1)
        self.lbl_sma = QtWidgets.QLabel(self.GB_body)
        self.lbl_sma.setObjectName("lbl_sma")
        self.gridLayout.addWidget(self.lbl_sma, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.GB_body)
        self.frame = QtWidgets.QFrame(bodyForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_ok = QtWidgets.QPushButton(self.frame)
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout.addWidget(self.btn_ok)
        self.btn_cancel = QtWidgets.QPushButton(self.frame)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(bodyForm)
        QtCore.QMetaObject.connectSlotsByName(bodyForm)
        bodyForm.setTabOrder(self.le_name, self.cb_star)
        bodyForm.setTabOrder(self.cb_star, self.le_mass)
        bodyForm.setTabOrder(self.le_mass, self.le_radius)
        bodyForm.setTabOrder(self.le_radius, self.le_sma)
        bodyForm.setTabOrder(self.le_sma, self.le_vel)
        bodyForm.setTabOrder(self.le_vel, self.le_inc)
        bodyForm.setTabOrder(self.le_inc, self.btn_ok)
        bodyForm.setTabOrder(self.btn_ok, self.btn_cancel)

    def retranslateUi(self, bodyForm):
        _translate = QtCore.QCoreApplication.translate
        bodyForm.setWindowTitle(_translate("bodyForm", "Orbital Body - Edit"))
        self.GB_body.setTitle(_translate("bodyForm", "Orbital Body"))
        self.lbl_radius.setText(_translate("bodyForm", "Radius (km):"))
        self.cb_star.setToolTip(_translate("bodyForm", "<html><head/><body><p>Stars will be placed in the middle of the simulation, and are immovable.</p></body></html>"))
        self.cb_star.setText(_translate("bodyForm", "Star"))
        self.le_radius.setToolTip(_translate("bodyForm", "<html><head/><body><p>Radius of the orbital body, in kilometers.</p></body></html>"))
        self.le_vel.setToolTip(_translate("bodyForm", "<html><head/><body><p>The mean orbital velocity, in kilometers per second.</p></body></html>"))
        self.le_sma.setToolTip(_translate("bodyForm", "<html><head/><body><p>The semi-major axis or mean radius of the orbit in kilometers.</p></body></html>"))
        self.le_inc.setToolTip(_translate("bodyForm", "<html><head/><body><p>Orbital inclination in degrees, 0 to 90.</p></body></html>"))
        self.le_mass.setToolTip(_translate("bodyForm", "<html><head/><body><p>Mass of the body, in kilograms.</p></body></html>"))
        self.le_name.setToolTip(_translate("bodyForm", "<html><head/><body><p>The name of this orbital body.</p></body></html>"))
        self.lbl_inc.setText(_translate("bodyForm", "Inclination (deg):"))
        self.lbl_name.setText(_translate("bodyForm", "Name:"))
        self.lbl_vel.setText(_translate("bodyForm", "Orbital Velocity (km/s):"))
        self.lbl_mass.setText(_translate("bodyForm", "Mass (kg):"))
        self.lbl_sma.setText(_translate("bodyForm", "Orbit Semi-Major Axis (km):"))
        self.btn_ok.setText(_translate("bodyForm", "Ok"))
        self.btn_cancel.setText(_translate("bodyForm", "Cancel"))

