# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SimMainWindow(object):
    def setupUi(self, SimMainWindow):
        SimMainWindow.setObjectName("SimMainWindow")
        SimMainWindow.resize(1132, 728)
        self.centralwidget = QtWidgets.QWidget(SimMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FRAME_LH = QtWidgets.QFrame(self.centralwidget)
        self.FRAME_LH.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.FRAME_LH.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FRAME_LH.setObjectName("FRAME_LH")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.FRAME_LH)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.WIDGET_LH = QtWidgets.QTabWidget(self.FRAME_LH)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WIDGET_LH.sizePolicy().hasHeightForWidth())
        self.WIDGET_LH.setSizePolicy(sizePolicy)
        self.WIDGET_LH.setAutoFillBackground(True)
        self.WIDGET_LH.setObjectName("WIDGET_LH")
        self.TAB_bodies = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TAB_bodies.sizePolicy().hasHeightForWidth())
        self.TAB_bodies.setSizePolicy(sizePolicy)
        self.TAB_bodies.setObjectName("TAB_bodies")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.TAB_bodies)
        self.verticalLayout_3.setContentsMargins(6, -1, 6, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.TAB_bodies)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_presets = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_presets.sizePolicy().hasHeightForWidth())
        self.lbl_presets.setSizePolicy(sizePolicy)
        self.lbl_presets.setObjectName("lbl_presets")
        self.horizontalLayout_4.addWidget(self.lbl_presets)
        self.cmb_preset = QtWidgets.QComboBox(self.frame_2)
        self.cmb_preset.setObjectName("cmb_preset")
        self.horizontalLayout_4.addWidget(self.cmb_preset)
        self.btn_loadpreset = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_loadpreset.sizePolicy().hasHeightForWidth())
        self.btn_loadpreset.setSizePolicy(sizePolicy)
        self.btn_loadpreset.setObjectName("btn_loadpreset")
        self.horizontalLayout_4.addWidget(self.btn_loadpreset)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.TAB_bodies)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gb_star = QtWidgets.QGroupBox(self.frame_4)
        self.gb_star.setObjectName("gb_star")
        self.formLayout = QtWidgets.QFormLayout(self.gb_star)
        self.formLayout.setObjectName("formLayout")
        self.lbl_starpreset = QtWidgets.QLabel(self.gb_star)
        self.lbl_starpreset.setObjectName("lbl_starpreset")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_starpreset)
        self.cb_starPreset = QtWidgets.QComboBox(self.gb_star)
        self.cb_starPreset.setObjectName("cb_starPreset")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_starPreset)
        self.lbl_starname = QtWidgets.QLabel(self.gb_star)
        self.lbl_starname.setObjectName("lbl_starname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_starname)
        self.le_starname = QtWidgets.QLineEdit(self.gb_star)
        self.le_starname.setText("")
        self.le_starname.setObjectName("le_starname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_starname)
        self.lbl_starmass = QtWidgets.QLabel(self.gb_star)
        self.lbl_starmass.setObjectName("lbl_starmass")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_starmass)
        self.le_starmass = QtWidgets.QLineEdit(self.gb_star)
        self.le_starmass.setObjectName("le_starmass")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_starmass)
        self.lbl_starradius = QtWidgets.QLabel(self.gb_star)
        self.lbl_starradius.setObjectName("lbl_starradius")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_starradius)
        self.le_starradius = QtWidgets.QLineEdit(self.gb_star)
        self.le_starradius.setObjectName("le_starradius")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_starradius)
        self.frame_5 = QtWidgets.QFrame(self.gb_star)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_starSave = QtWidgets.QPushButton(self.frame_5)
        self.btn_starSave.setObjectName("btn_starSave")
        self.horizontalLayout_3.addWidget(self.btn_starSave)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.frame_5)
        self.verticalLayout_6.addWidget(self.gb_star)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.lv_bodies = QtWidgets.QListView(self.TAB_bodies)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lv_bodies.sizePolicy().hasHeightForWidth())
        self.lv_bodies.setSizePolicy(sizePolicy)
        self.lv_bodies.setAutoFillBackground(True)
        self.lv_bodies.setFrameShape(QtWidgets.QFrame.Box)
        self.lv_bodies.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lv_bodies.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lv_bodies.setProperty("showDropIndicator", True)
        self.lv_bodies.setAlternatingRowColors(False)
        self.lv_bodies.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.lv_bodies.setIconSize(QtCore.QSize(10, 10))
        self.lv_bodies.setMovement(QtWidgets.QListView.Static)
        self.lv_bodies.setFlow(QtWidgets.QListView.TopToBottom)
        self.lv_bodies.setProperty("isWrapping", False)
        self.lv_bodies.setResizeMode(QtWidgets.QListView.Fixed)
        self.lv_bodies.setGridSize(QtCore.QSize(150, 30))
        self.lv_bodies.setViewMode(QtWidgets.QListView.ListMode)
        self.lv_bodies.setObjectName("lv_bodies")
        self.verticalLayout_3.addWidget(self.lv_bodies)
        self.frame_3 = QtWidgets.QFrame(self.TAB_bodies)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_rmbody = QtWidgets.QPushButton(self.frame_3)
        self.btn_rmbody.setObjectName("btn_rmbody")
        self.horizontalLayout_5.addWidget(self.btn_rmbody)
        self.btn_addbody = QtWidgets.QPushButton(self.frame_3)
        self.btn_addbody.setObjectName("btn_addbody")
        self.horizontalLayout_5.addWidget(self.btn_addbody)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.WIDGET_LH.addTab(self.TAB_bodies, "")
        self.TAB_options = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TAB_options.sizePolicy().hasHeightForWidth())
        self.TAB_options.setSizePolicy(sizePolicy)
        self.TAB_options.setAutoFillBackground(False)
        self.TAB_options.setObjectName("TAB_options")
        self.gridLayout = QtWidgets.QGridLayout(self.TAB_options)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setVerticalSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.le_nsteps = QtWidgets.QLineEdit(self.TAB_options)
        self.le_nsteps.setObjectName("le_nsteps")
        self.gridLayout.addWidget(self.le_nsteps, 5, 1, 1, 1)
        self.cmb_solmethod = QtWidgets.QComboBox(self.TAB_options)
        self.cmb_solmethod.setObjectName("cmb_solmethod")
        self.cmb_solmethod.addItem("")
        self.cmb_solmethod.addItem("")
        self.gridLayout.addWidget(self.cmb_solmethod, 0, 1, 1, 1)
        self.cmb_tsteps = QtWidgets.QComboBox(self.TAB_options)
        self.cmb_tsteps.setObjectName("cmb_tsteps")
        self.cmb_tsteps.addItem("")
        self.cmb_tsteps.addItem("")
        self.cmb_tsteps.addItem("")
        self.cmb_tsteps.addItem("")
        self.gridLayout.addWidget(self.cmb_tsteps, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(1, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)
        self.le_stepvalue = QtWidgets.QLineEdit(self.TAB_options)
        self.le_stepvalue.setObjectName("le_stepvalue")
        self.gridLayout.addWidget(self.le_stepvalue, 4, 0, 1, 1)
        self.lbl_solmeth = QtWidgets.QLabel(self.TAB_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_solmeth.sizePolicy().hasHeightForWidth())
        self.lbl_solmeth.setSizePolicy(sizePolicy)
        self.lbl_solmeth.setObjectName("lbl_solmeth")
        self.gridLayout.addWidget(self.lbl_solmeth, 0, 0, 1, 1)
        self.lbl_stepfreq = QtWidgets.QLabel(self.TAB_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_stepfreq.sizePolicy().hasHeightForWidth())
        self.lbl_stepfreq.setSizePolicy(sizePolicy)
        self.lbl_stepfreq.setObjectName("lbl_stepfreq")
        self.gridLayout.addWidget(self.lbl_stepfreq, 6, 0, 1, 1)
        self.le_stepfreq = QtWidgets.QLineEdit(self.TAB_options)
        self.le_stepfreq.setObjectName("le_stepfreq")
        self.gridLayout.addWidget(self.le_stepfreq, 6, 1, 1, 1)
        self.lbl_tsteps = QtWidgets.QLabel(self.TAB_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_tsteps.sizePolicy().hasHeightForWidth())
        self.lbl_tsteps.setSizePolicy(sizePolicy)
        self.lbl_tsteps.setObjectName("lbl_tsteps")
        self.gridLayout.addWidget(self.lbl_tsteps, 3, 0, 1, 1)
        self.lbl_solvetime = QtWidgets.QLabel(self.TAB_options)
        self.lbl_solvetime.setObjectName("lbl_solvetime")
        self.gridLayout.addWidget(self.lbl_solvetime, 7, 0, 1, 1)
        self.cmb_solvetime = QtWidgets.QComboBox(self.TAB_options)
        self.cmb_solvetime.setObjectName("cmb_solvetime")
        self.cmb_solvetime.addItem("")
        self.cmb_solvetime.addItem("")
        self.cmb_solvetime.addItem("")
        self.cmb_solvetime.addItem("")
        self.cmb_solvetime.addItem("")
        self.cmb_solvetime.addItem("")
        self.cmb_solvetime.addItem("")
        self.cmb_solvetime.addItem("")
        self.cmb_solvetime.setItemText(7, "")
        self.gridLayout.addWidget(self.cmb_solvetime, 7, 1, 1, 1)
        self.lbl_simdur = QtWidgets.QLabel(self.TAB_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_simdur.sizePolicy().hasHeightForWidth())
        self.lbl_simdur.setSizePolicy(sizePolicy)
        self.lbl_simdur.setObjectName("lbl_simdur")
        self.gridLayout.addWidget(self.lbl_simdur, 5, 0, 1, 1)
        self.lbl_multiprocess = QtWidgets.QLabel(self.TAB_options)
        self.lbl_multiprocess.setObjectName("lbl_multiprocess")
        self.gridLayout.addWidget(self.lbl_multiprocess, 1, 0, 1, 1)
        self.rb_multiprocess = QtWidgets.QRadioButton(self.TAB_options)
        self.rb_multiprocess.setText("")
        self.rb_multiprocess.setChecked(True)
        self.rb_multiprocess.setObjectName("rb_multiprocess")
        self.gridLayout.addWidget(self.rb_multiprocess, 1, 1, 1, 1)
        self.WIDGET_LH.addTab(self.TAB_options, "")
        self.verticalLayout_2.addWidget(self.WIDGET_LH)
        self.frame = QtWidgets.QFrame(self.FRAME_LH)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_reset = QtWidgets.QPushButton(self.frame)
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout_2.addWidget(self.btn_reset)
        self.btn_clear = QtWidgets.QPushButton(self.frame)
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout_2.addWidget(self.btn_clear)
        self.btn_plot = QtWidgets.QPushButton(self.frame)
        self.btn_plot.setObjectName("btn_plot")
        self.horizontalLayout_2.addWidget(self.btn_plot)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.FRAME_LH)
        self.FRAME_views = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FRAME_views.sizePolicy().hasHeightForWidth())
        self.FRAME_views.setSizePolicy(sizePolicy)
        self.FRAME_views.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.FRAME_views.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FRAME_views.setObjectName("FRAME_views")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.FRAME_views)
        self.verticalLayout.setObjectName("verticalLayout")
        self.WIDGET_viewTabs = QtWidgets.QTabWidget(self.FRAME_views)
        self.WIDGET_viewTabs.setObjectName("WIDGET_viewTabs")
        self.TAB_XY = QtWidgets.QWidget()
        self.TAB_XY.setObjectName("TAB_XY")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.TAB_XY)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gv_xy = PlotWidget(self.TAB_XY)
        self.gv_xy.setObjectName("gv_xy")
        self.verticalLayout_5.addWidget(self.gv_xy)
        self.WIDGET_viewTabs.addTab(self.TAB_XY, "")
        self.TAB_3D = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TAB_3D.sizePolicy().hasHeightForWidth())
        self.TAB_3D.setSizePolicy(sizePolicy)
        self.TAB_3D.setObjectName("TAB_3D")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.TAB_3D)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gv_3d = GLViewWidget(self.TAB_3D)
        self.gv_3d.setObjectName("gv_3d")
        self.verticalLayout_4.addWidget(self.gv_3d)
        self.WIDGET_viewTabs.addTab(self.TAB_3D, "")
        self.verticalLayout.addWidget(self.WIDGET_viewTabs)
        self.frame_7 = QtWidgets.QFrame(self.FRAME_views)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_focus_prv = QtWidgets.QPushButton(self.frame_7)
        self.btn_focus_prv.setObjectName("btn_focus_prv")
        self.horizontalLayout_6.addWidget(self.btn_focus_prv)
        self.lbl_body_focus = QtWidgets.QLabel(self.frame_7)
        self.lbl_body_focus.setObjectName("lbl_body_focus")
        self.horizontalLayout_6.addWidget(self.lbl_body_focus, 0, QtCore.Qt.AlignHCenter)
        self.btn_focus_next = QtWidgets.QPushButton(self.frame_7)
        self.btn_focus_next.setObjectName("btn_focus_next")
        self.horizontalLayout_6.addWidget(self.btn_focus_next)
        self.verticalLayout.addWidget(self.frame_7, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.FRAME_views)
        SimMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SimMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1132, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        SimMainWindow.setMenuBar(self.menubar)
        self.actionPreset = QtWidgets.QAction(SimMainWindow)
        self.actionPreset.setObjectName("actionPreset")
        self.actionExit = QtWidgets.QAction(SimMainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(SimMainWindow)
        self.WIDGET_LH.setCurrentIndex(1)
        self.cmb_tsteps.setCurrentIndex(0)
        self.WIDGET_viewTabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SimMainWindow)

    def retranslateUi(self, SimMainWindow):
        _translate = QtCore.QCoreApplication.translate
        SimMainWindow.setWindowTitle(_translate("SimMainWindow", "Orbit Simulations -- Joshua Fraustro"))
        self.lbl_presets.setText(_translate("SimMainWindow", "Presets:"))
        self.btn_loadpreset.setText(_translate("SimMainWindow", "Load"))
        self.gb_star.setTitle(_translate("SimMainWindow", "Star:"))
        self.lbl_starpreset.setText(_translate("SimMainWindow", "Preset:"))
        self.lbl_starname.setText(_translate("SimMainWindow", "Name:"))
        self.lbl_starmass.setText(_translate("SimMainWindow", "Mass:"))
        self.lbl_starradius.setText(_translate("SimMainWindow", "Radius:"))
        self.btn_starSave.setText(_translate("SimMainWindow", "Save"))
        self.btn_rmbody.setText(_translate("SimMainWindow", "Remove Body"))
        self.btn_addbody.setText(_translate("SimMainWindow", "Add Body"))
        self.WIDGET_LH.setTabText(self.WIDGET_LH.indexOf(self.TAB_bodies), _translate("SimMainWindow", "Bodies"))
        self.le_nsteps.setText(_translate("SimMainWindow", "100"))
        self.cmb_solmethod.setItemText(0, _translate("SimMainWindow", "Euler Integration"))
        self.cmb_solmethod.setItemText(1, _translate("SimMainWindow", "Sphere of Influence"))
        self.cmb_tsteps.setItemText(0, _translate("SimMainWindow", "Seconds"))
        self.cmb_tsteps.setItemText(1, _translate("SimMainWindow", "Minutes"))
        self.cmb_tsteps.setItemText(2, _translate("SimMainWindow", "Days"))
        self.cmb_tsteps.setItemText(3, _translate("SimMainWindow", "Years"))
        self.le_stepvalue.setText(_translate("SimMainWindow", "86400"))
        self.lbl_solmeth.setText(_translate("SimMainWindow", "Solution Method:"))
        self.lbl_stepfreq.setText(_translate("SimMainWindow", "Report Frequency:"))
        self.le_stepfreq.setText(_translate("SimMainWindow", "1"))
        self.lbl_tsteps.setText(_translate("SimMainWindow", "Time Step Value:"))
        self.lbl_solvetime.setText(_translate("SimMainWindow", "Maximum Solve Time (s):"))
        self.cmb_solvetime.setItemText(0, _translate("SimMainWindow", "Unlimited"))
        self.cmb_solvetime.setItemText(1, _translate("SimMainWindow", "5"))
        self.cmb_solvetime.setItemText(2, _translate("SimMainWindow", "10"))
        self.cmb_solvetime.setItemText(3, _translate("SimMainWindow", "20"))
        self.cmb_solvetime.setItemText(4, _translate("SimMainWindow", "30"))
        self.cmb_solvetime.setItemText(5, _translate("SimMainWindow", "45"))
        self.cmb_solvetime.setItemText(6, _translate("SimMainWindow", "60"))
        self.lbl_simdur.setText(_translate("SimMainWindow", "Number of Steps:"))
        self.lbl_multiprocess.setText(_translate("SimMainWindow", "Multiprocessing:"))
        self.WIDGET_LH.setTabText(self.WIDGET_LH.indexOf(self.TAB_options), _translate("SimMainWindow", "Options"))
        self.btn_reset.setText(_translate("SimMainWindow", "Reset"))
        self.btn_clear.setText(_translate("SimMainWindow", "Clear Plot"))
        self.btn_plot.setText(_translate("SimMainWindow", "Plot"))
        self.WIDGET_viewTabs.setTabText(self.WIDGET_viewTabs.indexOf(self.TAB_XY), _translate("SimMainWindow", "XY View"))
        self.WIDGET_viewTabs.setTabText(self.WIDGET_viewTabs.indexOf(self.TAB_3D), _translate("SimMainWindow", "3D View"))
        self.btn_focus_prv.setText(_translate("SimMainWindow", "<<"))
        self.lbl_body_focus.setText(_translate("SimMainWindow", "Body Focus"))
        self.btn_focus_next.setText(_translate("SimMainWindow", ">>"))
        self.menuFile.setTitle(_translate("SimMainWindow", "File"))
        self.menuHelp.setTitle(_translate("SimMainWindow", "Help"))
        self.actionPreset.setText(_translate("SimMainWindow", "Preset"))
        self.actionExit.setText(_translate("SimMainWindow", "Exit"))

from pyqtgraph import PlotWidget
from pyqtgraph.opengl import GLViewWidget
