# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SimMainWindow(object):
    def setupUi(self, SimMainWindow):
        SimMainWindow.setObjectName("SimMainWindow")
        SimMainWindow.resize(1132, 728)
        self.centralwidget = QtWidgets.QWidget(SimMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FRAME_LH = QtWidgets.QFrame(self.centralwidget)
        self.FRAME_LH.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.FRAME_LH.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FRAME_LH.setObjectName("FRAME_LH")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.FRAME_LH)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.WIDGET_LH = QtWidgets.QTabWidget(self.FRAME_LH)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WIDGET_LH.sizePolicy().hasHeightForWidth())
        self.WIDGET_LH.setSizePolicy(sizePolicy)
        self.WIDGET_LH.setAutoFillBackground(True)
        self.WIDGET_LH.setObjectName("WIDGET_LH")
        self.TAB_bodies = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TAB_bodies.sizePolicy().hasHeightForWidth())
        self.TAB_bodies.setSizePolicy(sizePolicy)
        self.TAB_bodies.setObjectName("TAB_bodies")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.TAB_bodies)
        self.verticalLayout_3.setContentsMargins(6, -1, 6, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.TAB_bodies)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_presets = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_presets.sizePolicy().hasHeightForWidth())
        self.lbl_presets.setSizePolicy(sizePolicy)
        self.lbl_presets.setObjectName("lbl_presets")
        self.horizontalLayout_4.addWidget(self.lbl_presets)
        self.cmb_preset = QtWidgets.QComboBox(self.frame_2)
        self.cmb_preset.setObjectName("cmb_preset")
        self.horizontalLayout_4.addWidget(self.cmb_preset)
        self.btn_loadpreset = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_loadpreset.sizePolicy().hasHeightForWidth())
        self.btn_loadpreset.setSizePolicy(sizePolicy)
        self.btn_loadpreset.setObjectName("btn_loadpreset")
        self.horizontalLayout_4.addWidget(self.btn_loadpreset)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.lv_bodies = QtWidgets.QListView(self.TAB_bodies)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lv_bodies.sizePolicy().hasHeightForWidth())
        self.lv_bodies.setSizePolicy(sizePolicy)
        self.lv_bodies.setAutoFillBackground(True)
        self.lv_bodies.setFrameShape(QtWidgets.QFrame.Box)
        self.lv_bodies.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lv_bodies.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lv_bodies.setProperty("showDropIndicator", True)
        self.lv_bodies.setObjectName("lv_bodies")
        self.verticalLayout_3.addWidget(self.lv_bodies)
        self.frame_3 = QtWidgets.QFrame(self.TAB_bodies)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_rmbody = QtWidgets.QPushButton(self.frame_3)
        self.btn_rmbody.setObjectName("btn_rmbody")
        self.horizontalLayout_5.addWidget(self.btn_rmbody)
        self.btn_addbody = QtWidgets.QPushButton(self.frame_3)
        self.btn_addbody.setObjectName("btn_addbody")
        self.horizontalLayout_5.addWidget(self.btn_addbody)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.WIDGET_LH.addTab(self.TAB_bodies, "")
        self.TAB_options = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TAB_options.sizePolicy().hasHeightForWidth())
        self.TAB_options.setSizePolicy(sizePolicy)
        self.TAB_options.setAutoFillBackground(False)
        self.TAB_options.setObjectName("TAB_options")
        self.gridLayout = QtWidgets.QGridLayout(self.TAB_options)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setVerticalSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_tsteps = QtWidgets.QLabel(self.TAB_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_tsteps.sizePolicy().hasHeightForWidth())
        self.lbl_tsteps.setSizePolicy(sizePolicy)
        self.lbl_tsteps.setObjectName("lbl_tsteps")
        self.gridLayout.addWidget(self.lbl_tsteps, 2, 0, 1, 1)
        self.cmb_simdur = QtWidgets.QComboBox(self.TAB_options)
        self.cmb_simdur.setObjectName("cmb_simdur")
        self.cmb_simdur.addItem("")
        self.cmb_simdur.addItem("")
        self.cmb_simdur.addItem("")
        self.cmb_simdur.addItem("")
        self.gridLayout.addWidget(self.cmb_simdur, 4, 1, 1, 1)
        self.le_simdur = QtWidgets.QLineEdit(self.TAB_options)
        self.le_simdur.setObjectName("le_simdur")
        self.gridLayout.addWidget(self.le_simdur, 4, 0, 1, 1)
        self.cmb_solvetime = QtWidgets.QComboBox(self.TAB_options)
        self.cmb_solvetime.setObjectName("cmb_solvetime")
        self.cmb_solvetime.addItem("")
        self.cmb_solvetime.addItem("")
        self.cmb_solvetime.addItem("")
        self.cmb_solvetime.addItem("")
        self.cmb_solvetime.addItem("")
        self.cmb_solvetime.addItem("")
        self.cmb_solvetime.addItem("")
        self.cmb_solvetime.addItem("")
        self.cmb_solvetime.setItemText(7, "")
        self.gridLayout.addWidget(self.cmb_solvetime, 5, 1, 1, 1)
        self.lbl_simdur = QtWidgets.QLabel(self.TAB_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_simdur.sizePolicy().hasHeightForWidth())
        self.lbl_simdur.setSizePolicy(sizePolicy)
        self.lbl_simdur.setObjectName("lbl_simdur")
        self.gridLayout.addWidget(self.lbl_simdur, 3, 0, 1, 1)
        self.cmb_tsteps = QtWidgets.QComboBox(self.TAB_options)
        self.cmb_tsteps.setObjectName("cmb_tsteps")
        self.cmb_tsteps.addItem("")
        self.cmb_tsteps.addItem("")
        self.cmb_tsteps.addItem("")
        self.cmb_tsteps.addItem("")
        self.cmb_tsteps.addItem("")
        self.gridLayout.addWidget(self.cmb_tsteps, 2, 1, 1, 1)
        self.lbl_solvetime = QtWidgets.QLabel(self.TAB_options)
        self.lbl_solvetime.setObjectName("lbl_solvetime")
        self.gridLayout.addWidget(self.lbl_solvetime, 5, 0, 1, 1)
        self.lbl_solmeth = QtWidgets.QLabel(self.TAB_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_solmeth.sizePolicy().hasHeightForWidth())
        self.lbl_solmeth.setSizePolicy(sizePolicy)
        self.lbl_solmeth.setObjectName("lbl_solmeth")
        self.gridLayout.addWidget(self.lbl_solmeth, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(1, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)
        self.cmb_solmethod = QtWidgets.QComboBox(self.TAB_options)
        self.cmb_solmethod.setObjectName("cmb_solmethod")
        self.cmb_solmethod.addItem("")
        self.cmb_solmethod.addItem("")
        self.cmb_solmethod.addItem("")
        self.cmb_solmethod.addItem("")
        self.gridLayout.addWidget(self.cmb_solmethod, 0, 1, 1, 1)
        self.WIDGET_LH.addTab(self.TAB_options, "")
        self.verticalLayout_2.addWidget(self.WIDGET_LH)
        self.frame = QtWidgets.QFrame(self.FRAME_LH)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_reset = QtWidgets.QPushButton(self.frame)
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout_2.addWidget(self.btn_reset)
        self.btn_clear = QtWidgets.QPushButton(self.frame)
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout_2.addWidget(self.btn_clear)
        self.btn_plot = QtWidgets.QPushButton(self.frame)
        self.btn_plot.setObjectName("btn_plot")
        self.horizontalLayout_2.addWidget(self.btn_plot)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout.addWidget(self.FRAME_LH)
        self.FRAME_views = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FRAME_views.sizePolicy().hasHeightForWidth())
        self.FRAME_views.setSizePolicy(sizePolicy)
        self.FRAME_views.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.FRAME_views.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FRAME_views.setObjectName("FRAME_views")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.FRAME_views)
        self.verticalLayout.setObjectName("verticalLayout")
        self.WIDGET_viewTabs = QtWidgets.QTabWidget(self.FRAME_views)
        self.WIDGET_viewTabs.setObjectName("WIDGET_viewTabs")
        self.TAB_XY = QtWidgets.QWidget()
        self.TAB_XY.setObjectName("TAB_XY")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.TAB_XY)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.WIDGET_viewTabs.addTab(self.TAB_XY, "")
        self.TAB_3D = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TAB_3D.sizePolicy().hasHeightForWidth())
        self.TAB_3D.setSizePolicy(sizePolicy)
        self.TAB_3D.setObjectName("TAB_3D")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.TAB_3D)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.WIDGET_viewTabs.addTab(self.TAB_3D, "")
        self.verticalLayout.addWidget(self.WIDGET_viewTabs)
        self.horizontalLayout.addWidget(self.FRAME_views)
        SimMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SimMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1132, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        SimMainWindow.setMenuBar(self.menubar)
        self.actionPreset = QtWidgets.QAction(SimMainWindow)
        self.actionPreset.setObjectName("actionPreset")
        self.actionExit = QtWidgets.QAction(SimMainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(SimMainWindow)
        self.WIDGET_LH.setCurrentIndex(0)
        self.cmb_tsteps.setCurrentIndex(2)
        self.WIDGET_viewTabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SimMainWindow)

    def retranslateUi(self, SimMainWindow):
        _translate = QtCore.QCoreApplication.translate
        SimMainWindow.setWindowTitle(_translate("SimMainWindow", "Orbit Simulations -- Joshua Fraustro"))
        self.lbl_presets.setText(_translate("SimMainWindow", "Presets:"))
        self.btn_loadpreset.setText(_translate("SimMainWindow", "Load"))
        self.btn_rmbody.setText(_translate("SimMainWindow", "Remove Body"))
        self.btn_addbody.setText(_translate("SimMainWindow", "Add Body"))
        self.WIDGET_LH.setTabText(self.WIDGET_LH.indexOf(self.TAB_bodies), _translate("SimMainWindow", "Bodies"))
        self.lbl_tsteps.setText(_translate("SimMainWindow", "Time Steps:"))
        self.cmb_simdur.setItemText(0, _translate("SimMainWindow", "seconds"))
        self.cmb_simdur.setItemText(1, _translate("SimMainWindow", "minutes"))
        self.cmb_simdur.setItemText(2, _translate("SimMainWindow", "days"))
        self.cmb_simdur.setItemText(3, _translate("SimMainWindow", "years"))
        self.cmb_solvetime.setItemText(0, _translate("SimMainWindow", "Unlimited"))
        self.cmb_solvetime.setItemText(1, _translate("SimMainWindow", "5"))
        self.cmb_solvetime.setItemText(2, _translate("SimMainWindow", "10"))
        self.cmb_solvetime.setItemText(3, _translate("SimMainWindow", "20"))
        self.cmb_solvetime.setItemText(4, _translate("SimMainWindow", "30"))
        self.cmb_solvetime.setItemText(5, _translate("SimMainWindow", "45"))
        self.cmb_solvetime.setItemText(6, _translate("SimMainWindow", "60"))
        self.lbl_simdur.setText(_translate("SimMainWindow", "Simulation Duration:"))
        self.cmb_tsteps.setItemText(0, _translate("SimMainWindow", "Fine"))
        self.cmb_tsteps.setItemText(1, _translate("SimMainWindow", "Short"))
        self.cmb_tsteps.setItemText(2, _translate("SimMainWindow", "Medium"))
        self.cmb_tsteps.setItemText(3, _translate("SimMainWindow", "Long"))
        self.cmb_tsteps.setItemText(4, _translate("SimMainWindow", "Coarse"))
        self.lbl_solvetime.setText(_translate("SimMainWindow", "Maximum Solve Time (s):"))
        self.lbl_solmeth.setText(_translate("SimMainWindow", "Solution Method:"))
        self.cmb_solmethod.setItemText(0, _translate("SimMainWindow", "Euler Integration"))
        self.cmb_solmethod.setItemText(1, _translate("SimMainWindow", "RK4"))
        self.cmb_solmethod.setItemText(2, _translate("SimMainWindow", "Sphere of Influence"))
        self.cmb_solmethod.setItemText(3, _translate("SimMainWindow", "Distance Softened"))
        self.WIDGET_LH.setTabText(self.WIDGET_LH.indexOf(self.TAB_options), _translate("SimMainWindow", "Options"))
        self.btn_reset.setText(_translate("SimMainWindow", "Reset"))
        self.btn_clear.setText(_translate("SimMainWindow", "Clear Plot"))
        self.btn_plot.setText(_translate("SimMainWindow", "Plot"))
        self.WIDGET_viewTabs.setTabText(self.WIDGET_viewTabs.indexOf(self.TAB_XY), _translate("SimMainWindow", "XY View"))
        self.WIDGET_viewTabs.setTabText(self.WIDGET_viewTabs.indexOf(self.TAB_3D), _translate("SimMainWindow", "3D View"))
        self.menuFile.setTitle(_translate("SimMainWindow", "File"))
        self.menuHelp.setTitle(_translate("SimMainWindow", "Help"))
        self.actionPreset.setText(_translate("SimMainWindow", "Preset"))
        self.actionExit.setText(_translate("SimMainWindow", "Exit"))

