# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\starWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_starPresetDialog(object):
    def setupUi(self, starPresetDialog):
        starPresetDialog.setObjectName("starPresetDialog")
        starPresetDialog.resize(1067, 626)
        self.verticalLayout = QtWidgets.QVBoxLayout(starPresetDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(starPresetDialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_starselect = QtWidgets.QLabel(self.frame_4)
        self.lbl_starselect.setObjectName("lbl_starselect")
        self.verticalLayout_2.addWidget(self.lbl_starselect)
        self.lv_stars = QtWidgets.QListView(self.frame_4)
        self.lv_stars.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lv_stars.setObjectName("lv_stars")
        self.verticalLayout_2.addWidget(self.lv_stars)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gb_starinfo = QtWidgets.QGroupBox(self.frame)
        self.gb_starinfo.setStyleSheet("")
        self.gb_starinfo.setObjectName("gb_starinfo")
        self.formLayout = QtWidgets.QFormLayout(self.gb_starinfo)
        self.formLayout.setVerticalSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.lbl_name = QtWidgets.QLabel(self.gb_starinfo)
        self.lbl_name.setObjectName("lbl_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_name)
        self.le_name = QtWidgets.QLineEdit(self.gb_starinfo)
        self.le_name.setReadOnly(True)
        self.le_name.setObjectName("le_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_name)
        self.lbl_altname = QtWidgets.QLabel(self.gb_starinfo)
        self.lbl_altname.setObjectName("lbl_altname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_altname)
        self.le_altname = QtWidgets.QLineEdit(self.gb_starinfo)
        self.le_altname.setReadOnly(True)
        self.le_altname.setObjectName("le_altname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_altname)
        self.lbl_dist = QtWidgets.QLabel(self.gb_starinfo)
        self.lbl_dist.setObjectName("lbl_dist")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_dist)
        self.le_dist = QtWidgets.QLineEdit(self.gb_starinfo)
        self.le_dist.setReadOnly(True)
        self.le_dist.setObjectName("le_dist")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_dist)
        self.lbl_specclass = QtWidgets.QLabel(self.gb_starinfo)
        self.lbl_specclass.setObjectName("lbl_specclass")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_specclass)
        self.le_specclass = QtWidgets.QLineEdit(self.gb_starinfo)
        self.le_specclass.setReadOnly(True)
        self.le_specclass.setObjectName("le_specclass")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.le_specclass)
        self.lbl_solmass = QtWidgets.QLabel(self.gb_starinfo)
        self.lbl_solmass.setObjectName("lbl_solmass")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_solmass)
        self.le_solmass = QtWidgets.QLineEdit(self.gb_starinfo)
        self.le_solmass.setAutoFillBackground(False)
        self.le_solmass.setReadOnly(True)
        self.le_solmass.setObjectName("le_solmass")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.le_solmass)
        self.lbl_mass = QtWidgets.QLabel(self.gb_starinfo)
        self.lbl_mass.setObjectName("lbl_mass")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_mass)
        self.le_mass = QtWidgets.QLineEdit(self.gb_starinfo)
        self.le_mass.setReadOnly(True)
        self.le_mass.setObjectName("le_mass")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.le_mass)
        self.lbl_solradius = QtWidgets.QLabel(self.gb_starinfo)
        self.lbl_solradius.setObjectName("lbl_solradius")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lbl_solradius)
        self.le_radius = QtWidgets.QLineEdit(self.gb_starinfo)
        self.le_radius.setReadOnly(True)
        self.le_radius.setObjectName("le_radius")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.le_radius)
        self.lbl_radius = QtWidgets.QLabel(self.gb_starinfo)
        self.lbl_radius.setObjectName("lbl_radius")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lbl_radius)
        self.le_radius_2 = QtWidgets.QLineEdit(self.gb_starinfo)
        self.le_radius_2.setReadOnly(True)
        self.le_radius_2.setObjectName("le_radius_2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.le_radius_2)
        self.lbl_temp = QtWidgets.QLabel(self.gb_starinfo)
        self.lbl_temp.setObjectName("lbl_temp")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lbl_temp)
        self.le_temp = QtWidgets.QLineEdit(self.gb_starinfo)
        self.le_temp.setReadOnly(True)
        self.le_temp.setObjectName("le_temp")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.le_temp)
        self.lbl_absmag = QtWidgets.QLabel(self.gb_starinfo)
        self.lbl_absmag.setObjectName("lbl_absmag")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.lbl_absmag)
        self.le_mag = QtWidgets.QLineEdit(self.gb_starinfo)
        self.le_mag.setReadOnly(True)
        self.le_mag.setObjectName("le_mag")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.le_mag)
        self.verticalLayout_3.addWidget(self.gb_starinfo)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gv_star = GLViewWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gv_star.sizePolicy().hasHeightForWidth())
        self.gv_star.setSizePolicy(sizePolicy)
        self.gv_star.setObjectName("gv_star")
        self.verticalLayout_4.addWidget(self.gv_star)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(starPresetDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(starPresetDialog)
        self.buttonBox.accepted.connect(starPresetDialog.accept)
        self.buttonBox.rejected.connect(starPresetDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(starPresetDialog)

    def retranslateUi(self, starPresetDialog):
        _translate = QtCore.QCoreApplication.translate
        starPresetDialog.setWindowTitle(_translate("starPresetDialog", "Star Selector"))
        self.lbl_starselect.setText(_translate("starPresetDialog", "Select a Star from the Catalog:"))
        self.gb_starinfo.setTitle(_translate("starPresetDialog", "Selected Star:"))
        self.lbl_name.setText(_translate("starPresetDialog", "Name:"))
        self.lbl_altname.setText(_translate("starPresetDialog", "Alternate Names:"))
        self.lbl_dist.setText(_translate("starPresetDialog", "Distance to Sun:"))
        self.lbl_specclass.setText(_translate("starPresetDialog", "Spectral Class"))
        self.lbl_solmass.setText(_translate("starPresetDialog", "Solar Masses:"))
        self.lbl_mass.setText(_translate("starPresetDialog", "Mass (kg):"))
        self.lbl_solradius.setText(_translate("starPresetDialog", "Solar Radius:"))
        self.lbl_radius.setText(_translate("starPresetDialog", "Radius (km):"))
        self.lbl_temp.setText(_translate("starPresetDialog", "Surface Temperature:"))
        self.lbl_absmag.setText(_translate("starPresetDialog", "Absolute Magnitude:"))

from pyqtgraph.opengl import GLViewWidget
